"""AgentKernel — generic agent perception-decision-execution framework.

This package defines the core protocols and data types for building
vision-driven autonomous agents. It is game-agnostic; application-specific
logic lives in adapter packages.
"""
from __future__ import annotations

from agent_kernel.types import (
    ActionableElement,
    DesktopNode,
    DesktopTree,
    SceneObject,
    WorldStateGraph,
    SceneGraph,
    Affordance,
    SemanticObservation,
    AgentGoal,
    TaskSpec,
    RuntimeOverride,
    OperatorCommand,
    PlannedStep,
    ActionPlan,
    SkillStep,
    SkillRecipe,
    ActionPrimitive,
    SemanticAction,
    ActionContract,
    ThreatSignal,
    CombatCommand,
    PhysicalReceipt,
    StepResult,
    Experience,
    ObservationClaim,
    StateDeltaClaim,
    GoalResult,
    CapsulePatchProposal,
    ClaimEvidence,
    MissionNode,
    MissionGraph,
    RouteSegment,
    RepairPatch,
)
from agent_kernel.claim_bridge import ClaimBridgeResult, KernelClaimBridge
from agent_kernel.embodied_runtime import (
    CombatModeDetector,
    DailyCommissionDryRunRuntime,
    DailyCommissionObjective,
    DailyCommissionTrace,
    EmbodiedAction,
    HybridOpenWorldNavigator,
    NavigationFrame,
    RealTimeCombatPolicy,
    TeamCombatRuntime,
    TeamMemberRuntime,
)
from agent_kernel.skill_lookup import KernelSkillRecipeLookup
from agent_kernel.protocols import (
    GameCapsule,
    MemoryStore,
    Planner,
    SkillRecipeLookup,
    PerceptionProvider,
    CerebrumPlanner,
    SuccessChecker,
    ClaimAdjudicator,
    ExecutionProvider,
    InputLeaseManager,
    SpinalReflexAgent,
    BrainstemNavigator,
    DialogueController,
    CerebellumController,
    CerebrumAgent,
    CompanionAgent,
)

__all__ = [
    # Types
    "ActionableElement",
    "DesktopNode",
    "DesktopTree",
    "SceneObject",
    "WorldStateGraph",
    "SceneGraph",
    "Affordance",
    "SemanticObservation",
    "AgentGoal",
    "TaskSpec",
    "RuntimeOverride",
    "OperatorCommand",
    "PlannedStep",
    "ActionPlan",
    "SkillStep",
    "SkillRecipe",
    "ActionPrimitive",
    "SemanticAction",
    "ActionContract",
    "ThreatSignal",
    "CombatCommand",
    "PhysicalReceipt",
    "StepResult",
    "Experience",
    "ObservationClaim",
    "StateDeltaClaim",
    "GoalResult",
    "CapsulePatchProposal",
    "ClaimEvidence",
    "MissionNode",
    "MissionGraph",
    "RouteSegment",
    "RepairPatch",
    "ClaimBridgeResult",
    "KernelClaimBridge",
    "CombatModeDetector",
    "DailyCommissionDryRunRuntime",
    "DailyCommissionObjective",
    "DailyCommissionTrace",
    "EmbodiedAction",
    "HybridOpenWorldNavigator",
    "NavigationFrame",
    "RealTimeCombatPolicy",
    "TeamCombatRuntime",
    "TeamMemberRuntime",
    "KernelSkillRecipeLookup",
    # Protocols
    "GameCapsule",
    "MemoryStore",
    "Planner",
    "SkillRecipeLookup",
    "PerceptionProvider",
    "CerebrumPlanner",
    "SuccessChecker",
    "ClaimAdjudicator",
    "ExecutionProvider",
    "InputLeaseManager",
    "SpinalReflexAgent",
    "BrainstemNavigator",
    "DialogueController",
    "CerebellumController",
    "CerebrumAgent",
    "CompanionAgent",
]
